"""Write web/data/site-data.js: the numbers the pages draw, read from results/.

  python3 web/build.py          (run from the project root; re-run after results change)

The pages stay plain HTML; this script only refreshes the data they load. The hero crop is the
ball labelled in test frame 121364_7_8; its position in the 1920x1080 frame is computed here so the
page can phase the stride-8 grid to the full frame.
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
WEB = ROOT / "web"
CROP_W, CROP_H, FRAME_W, FRAME_H = 192, 128, 1920, 1080


def runs():
    out = {}
    for f in sorted((ROOT / "results").glob("*/metrics.json")):
        r = json.loads(f.read_text())
        if "run_name" not in r:  # add-on studies (e.g. roi_sahi) are read separately below
            continue
        ball = next(c for c in r["per_class"] if c["class"] == "ball")
        v = f.parent / "val_metrics.json"
        val = next(c for c in json.loads(v.read_text())["per_class"] if c["class"] == "ball")["mAP50_95"] if v.exists() else None
        out[r["run_name"]] = {"ball": ball["mAP50_95"], "ball50": ball["mAP50"], "ballR": ball["recall"],
                              "all": r["overall"]["mAP50_95"], "fps": r["inference_fps"], "batch": r["batch"],
                              "min": r["train_minutes"], "val_ball": val}
    return out


def ball_crop():
    """Same crop rule as the asset step: 192x128 native px centred on the labelled ball."""
    lbl = next((ROOT / "frames/test_labels").glob("121364_7_8_png*.txt"))
    cx, cy, bw, bh = next(list(map(float, l.split()[1:])) for l in lbl.read_text().splitlines() if l.split()[0] == "0")
    cx, cy, bw, bh = cx * FRAME_W, cy * FRAME_H, bw * FRAME_W, bh * FRAME_H
    x0, y0 = int(cx - CROP_W / 2), int(cy - CROP_H / 2)
    return {"w": CROP_W, "h": CROP_H, "x0": x0, "y0": y0,
            "ball": {"x": round(cx - x0 - bw / 2, 2), "y": round(cy - y0 - bh / 2, 2), "w": round(bw, 2), "h": round(bh, 2)}}


def optional(path):
    """Results of the later add-on studies; the pages hide a panel whose data is missing."""
    p = ROOT / "results" / path
    return json.loads(p.read_text()) if p.exists() else None


data = {"runs": runs(), "crop": ball_crop(),
        "roi_sahi": optional("roi_sahi/metrics.json"),
        "ball_gaps": optional("ball_gaps/stats.json"),
        "shape": optional("tactical_v2/stats.json")}
out = WEB / "data" / "site-data.js"
out.parent.mkdir(exist_ok=True)
out.write_text("// Generated by web/build.py from results/. Do not edit by hand.\nwindow.BALLHAWK = "
               + json.dumps(data, indent=1) + ";\n")
print(f"{out.relative_to(ROOT)} {out.stat().st_size / 1024:.1f} KB")
